### ISSUE TITLE
Can't get rates to work.

### ISSUE THREAD

**Issue by zoltrain** [kevinjqiu/pat#12]
I common pattern I have for alerting is to calculate the error rate for a service.

I started out with a complex rule. that takes the amount of non OK grpc return codes, and divides them by the total request, then multiply by a 100 to get the %.

```sum(rate(grpc_server_handled_total{grpc_type="unary",grpc_code="Unknown"}[1m])) by (grpc_service) / sum(rate(grpc_server_started_total{grpc_type="unary"}[1m])) by (grpc_service) * 100.0 > 5 ```

I couldn't get a fixture that allowed me to get an alert to fire for this query.

So I then asked, does pat support sum/rate type queries on range-vectors?

This is my example rule + alert rule setup.

alert rule:

```groups:
- name: service.rules
  rules:
  - alert: HighErrorRates
    expr: sum(rate(grpc_server_handled_total[1m])) >= 2 
    for: 5m
    labels:
      severity: critical

```

pat test:

```
name: Test GRPC service errors
rules:
  fromFile: ../alerts/service.yaml
fixtures:
  - duration: 1m
    metrics:
      - grpc_server_handled_total{grpc_service="test.Test"} 2 4 6 8 10 12 14 16 18 20 22
assertions:
  - at: 5m
    expected:
      - alertname: HighErrorRates
        alertstate: pending
        severity: critical
        grpc_service: test.Test
  - at: 10m
    expected:
      - alertname: HighErrorRates
        alertstate: firing
        severity: critical
        grpc_service: test.Test
```

from my understanding of a fixture, this should give me a range-vector where each value in `grpc_server_handled_total{grpc_service="test.Test"} 2 4 6 8 10 12 14 16 18 20 22` is added to it every 1m

yet I never get anything firing in the above case?

I may just be misunderstanding how fixtures work? 

It might be good to add an example of a more complex query, like a rate over a range vector, or something like rate over a quantile in a histogram?

In any case, thanks for your work on this! It's something I'd love to use for testing our alerts, we have a lot!

**Comment by kevinjqiu** [comment]
> So I then asked, does pat support sum/rate type queries on range-vectors?

It does.  It uses the prometheus' query and storage engine under the hood.

I think a future improvement to this would be exposing the prometheus storage and query engine as a REPL in Pat so expressions can be tested adhoc.

I'll have a look into this some time this evening.  Thanks for reporting the issue.

**Comment by kevinjqiu** [comment]
@zoltrain OK I figured it out... Prometheus' [`rate` function](https://prometheus.io/docs/prometheus/latest/querying/functions/#rate()) calculates the "per-second rate" of a metric.  Because you're aggregating it by `1m`, you need to multiply it by `60`.

This rule works:

```
groups:                                                                                                                                                                                                                                                                                                                       
- name: service.rules                                                                                                                                                                                                                                                                                                         
  rules:                                                                                                                                                                                                                                                                                                                      
    - alert: HighErrorRates                                                                                                                                                                                                                                                                                                   
      expr: rate(grpc_server_handled_total[1m])*60 >= 2                                                                                                                                                                                                                                                                       
      for: 5m                                                                                                                                                                                                                                                                                                                 
      labels:                                                                                                                                                                                                                                                                                                                 
        severity: critical                                                                                                                                                                                                                                                                                                    
```

```
$ ./pat test.yaml 
=== RUN   Test_GRPC_service_errors_at_5m
--- PASS: Test_GRPC_service_errors_at_5m (0.00s)
=== RUN   Test_GRPC_service_errors_at_10m
--- PASS: Test_GRPC_service_errors_at_10m (0.00s)
PASS
```

Let me know if this answers your question.  I'll close this ticket for now.
